### PR TITLE
Fix: consistency of invalid command format messages 

### LINKED ISSUE #288: Fix formatting for invalid command format messages

### PR DESCRIPTION
**Pull request by Nijnxw**
Fix #288 
Close #288 

What is has been done in this PR:

**Standardise format for "invalid command format" messages**
* Add newline characters
* Consistent coding style across all command files
* GUI _Result Display_ for different methods to use command:
```
Invalid command format! 
delgrp: Deletes an existing tutorial group.
Parameter: grp/GROUP_NAME
Example: delgrp grp/G01
```
```
Invalid command format! 
markpresent: Marks a specific student or all students present from a lesson.
Parameters (3 methods):
1. all
2. name/STUDENT_NAME matric/STUDENT_NUMBER
3. INDEX (must be a positive integer)
Examples:
1. markpresent all
2. markpresent name/Aaron Tan matric/A0123456A
3. markpresent 1
```

**Standardise use of sample data & command examples**
* Student names in alphabetical orders (ie `Aaron`, `Benjamin`, `Catherine`, `David`)
* Student numbers are `A0123456X`, where `X` is the first character of the name (ie `Aaron`'s matric is `A0123456A`)

**Standardise test case examples in `TypicalXYZ.java` and `CommandTestUtil.java`**
* Standard groups: `G01` (Default in GroupBuilder), `G02`, `G04`
* Standard lessons: `1-1` (Default in LessonBuilder), `1-2`, `2-1`, `2-2`
* Standard students: `AARON` (Default in StudentBuilder), `BENJAMIN`, `CATHERINE`, `DAVID`
* Standard questions: `What is the deadline for the report?` (Default in QuestionBuilder), `When is the consultation held?`

**Consistent command descriptions**
* `viewXYZ` command descriptions all starts with "Displays ..."
* Standardise to use "tutorial groups" and "tutorial lessons" instead of "groups" and "lessons"

**Consistent parameter names and restrictions**
* Add restriction message for `INDEX`: must be a positive integer
* Add restriction message for `SCORE`, `SCORE_TO_ADD`, `SCORE_TO_SUBTRACT`: must be an integer from 0 to 5
* Rename `GROUP` and `LESSON` to `GROUP_NAME` and `LESSON_NAME` to follow UG
* Rename `PATH` to `PATH_TO_XLSX` to follow UG

### CODE REVIEW

File: src/main/java/team/serenity/model/util/SampleDataUtil.java [hunk 1]
```diff
@@ -69,19 +77,11 @@ public static ReadOnlySerenity getSampleSerenity() {
...
-     */
-    public static Set<Lesson> getLessonSet(Lesson... lessons) {
-        return Arrays.stream(lessons)
-            .collect(Collectors.toSet());
-    }
-
     public static Question[] getSampleQuestion() {
         return new Question[]{
-            new Question(new GroupName("G01"), new LessonName("1-1"),
+            new Question(new GroupName("G01"), LESSON_1_1,
```
Comment (chunyongg) [inline src/main/java/team/serenity/model/util/SampleDataUtil.java]: Since `LESSSON_1_1` is defined, perhaps define a `GROUP_G01` as well instead of `new GroupName('G01')` ?

Comment (Nijnxw) [reply src/main/java/team/serenity/model/util/SampleDataUtil.java]: Good suggestion! Ill add a new field for `GroupName` as well to be consistent :)

**Review by chunyongg — APPROVED** [review]
