### PR TITLE
Fix bug for addgrp invalid file path error message

### LINKED ISSUE #165: Bug: Addgrp command does not show error message when file path entered is invalid

### PR DESCRIPTION
**Pull request by Nijnxw**
Fix #165

### CODE REVIEW

File: src/main/java/team/serenity/model/group/Group.java [hunk 1]
```diff
@@ -46,6 +46,23 @@ public Group(String groupName, String filePath) {
         this.lessons.setElementsWithList(new ArrayList<>(util.readLessonsFromXlsx(studentsInfo)));
     }
 
+    /**
+     * Constructs a {@code Group}
+     *
+     * @param groupName     A valid group name.
```
Comment (chunyongg) [inline src/main/java/team/serenity/model/group/Group.java]: Too much spacing here?

**Review by chunyongg — APPROVED** [review]
